config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users
  resources :blogs
  resources :likes
  resources :comments
  match '/login' => 'sessions#new', :via => [:get], :as => 'new_sessions'
  match '/signup' => 'users#new', :via => [:get], :as => 'new_users'

  root 'sessions#new'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users_liked, through: :likes, source: :user
  validates :content, presence: true
  has_many :comments, dependent: :destroy
  has_many :users_commented, through: :comments, source: :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  validates :content, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true
  has_many :blogs
  has_many :likes, dependent: :destroy
  has_many :blogs_liked, through: :likes, source: :blog
  has_many :comments, dependent: :destroy
  has_many :blogs_commented, through: :comments, source: :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_login
  	redirect_to new_sessions_path if session[:user_id] == nil
  end

  def require_correct_user
  	user = User.find(params[:id])
  	redirect_to user_path(current_user) if current_user != user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :require_login, only: [:index, :create, :destroy]
	before_action :require_correct_user, only: [:show, :edit, :update, :destroy]

	def new 
		@blog = Blog.new
	end 

	def index
		@blogs = Blog.all
		@userlikes = Like.all
		@comment = Comment.new

		respond_to do |format|
		   format.html # show.html.erb
		   format.json { render json: @blogs.to_json(:include => [:comments, :likes])}
		 end
	end 

	def edit
		@blog = Blog.find(params[:id])
	end 

	def update
		blog = Blog.find(params[:id])
		blog.update_attributes(blog_params)
		redirect_to user_path(current_user)
	end 

	def show
		@blog = Blog.find(params[:id])
	

		respond_to do |format|
		   format.html # show.html.erb
		   format.json { render json: @blog.to_json(:include => [:comments, :likes])}
		 end
	end 

	def destroy
		blog = Blog.find(params[:id])
		blog.destroy if blog.user == current_user
		redirect_to user_path(current_user)
	end 

	def create
		@blog = current_user.blogs.build(blog_params)
		if @blog.save
			redirect_to user_path(current_user)
		else
			redirect_to user_path(current_user)
		end
	end 


	private

	def blog_params
		params.require(:blog).permit(:content, :blog_id, :user_id)
	end 

	def require_correct_user
		user = Blog.find(params[:id]).user
		redirect_to user_path(current_user) if current_user != user
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_login, only: [:index, :create, :destroy]

	def index

	end 


	def create 
		user = User.find(params[:user_id])
		blog = Blog.find(params[:blog_id])
		Comment.create(user: user, blog: blog, content: comment_params[:content])
		redirect_to user_path(current_user)
	end 

	def destroy
		comment = Comment.find(params[:id])
		comment.destroy if comment.user == current_user
		redirect_to user_path(current_user)
	end 

	private
	def comment_params
		params.require(:comment).permit(:content, :blog_id, :user_id)
	end 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :require_login, only: [:index, :create, :destroy]
	# before_action :require_correct_user, only: [:show, :edit, :update, :destroy]


	def index
		redirect_to blogs_path
	end 

	def new 

	end 

	def create
		user = User.find(params[:user_id])
		blog = Blog.find(params[:blog_id])
		Like.create(user: user, blog: blog)
		redirect_to blogs_path
	end 


	def destroy 
		like = Like.find(params[:id])
		like.destroy
		redirect_to blogs_path
	end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new 

	end



	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
		    session[:user_id] = user.id
		    redirect_to user
		    puts "Authenticated"
		 else
		    redirect_to new_session_path
		    flash[:errors] = "Invalid"
		    puts "Not authenticated"
		 end
	end

	def destroy
		session[:user_id] = nil
		redirect_to new_session_path
	end   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, except: [:new, :create]
	before_action :require_correct_user, only: [:show, :edit, :update, :destroy]

	
	def index

	end 

	def new
		@user = User.new

	end 

	def create
		@user = User.new(user_params)
		if User.create(user_params).valid? 
			puts "VALID"
			User.create(user_params)
			last_user = User.last
			session[:user_id] = last_user.id
			redirect_to user_path(last_user.id)
		else
			flash[:errors] =  "can't be blank. invalid" 
			puts "INVALID"
			redirect_to new_user_path
		end 
	end

	def edit
		@user = User.find(params[:id])
	end  

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		puts @user.errors.full_messages
		redirect_to user_path(params[:id])
	end 

	def destroy 
		session[:user_id] = nil
		User.find(params[:id]).destroy
		redirect_to new_session_path
	end

	def show
		@user = User.find(params[:id])
		@userBlog = User.find(params[:id]).blogs.all
		@blog = Blog.new
		@comment = Comment.new
	end 


	private 
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def blog_params
		params.require(:blog).permit(:content)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_for(@blog, url: blog_path, html: {method: "patch"}) do |f| %> 
<%=	f.label :content, "New Blog" %> 
<%= f.text_field :content, class: 'form-control' %> 
<br>
<%= f.submit "Edit Blog", class: "btn btn-primary" %> 
<br>
<br>
<br>
<% end %> 

app/views/blogs/index.html.erb
<div class="row">
	<h1 class="col-md-6 col-md-offset-4"> All Blogs </h1>
</div>

<div class="row">
	<div class="col-md-12">
		<% @blogs.each do |u| %>

		<div id="single_post"> 

			<p>  <%= link_to  u.content, blog_path(u.id), class: "navbar-brand" %></p> 
			<br>
			<br>
			<br>
			<p div class="col-md-1"> <%= u.likes.count %> likes </p>
			
			<% if !Like.where("user_id =  ? and blog_id =  ?", current_user.id, u.id).any? %> 
			<%= button_to "Like", {:controller => :likes, :action => 'create', :blog_id => u.id, :user_id => current_user.id}, :method => "post", class: "btn btn-primary" %>
			<% else %> 
			<%= button_to "Unlike", {:controller => :likes, :action => 'destroy', :id => Like.where("user_id =  ? and blog_id =  ?", current_user.id, u.id).first }, :method => "delete", class: "btn btn-primary" %>
			<% end %> 

			<br>
			<% u.comments.each do |c|  %> 
			<p> <%= c.user.name %>: <%= c.content %> 
				<% if current_user.id == c.user_id %> 
				<%= button_to "Delete comment", {:controller => :comments, :action => 'destroy', :id => c.id}, :method => "delete", class: "btn btn-primary " %>
				<% end %> 	
			</p>
			<% end %> 
			<br>

			<br>
			<% if current_user.id == u.user.id %> 
			<%= button_to "Delete blog", {:controller => :blogs, :action => 'destroy', :id => u.id}, :method => "delete", class: "btn btn-danger" %>
			<br>
			<%= button_to "Edit blog", {:controller => :blogs, :action => 'edit', :id => u.id}, :method => "get", class: "btn btn-primary" %>
			<% end %>


			<br>
			<%= form_for(@comment, url: comments_path, html: {method: "post"}) do |f| %> 

			<%= hidden_field_tag(:blog_id, u.id) %>
			<%= hidden_field_tag(:user_id, current_user.id) %>


			<%= f.text_field :content, class: 'form-control', placeholder: "Write a comment..." %> 
			<br>
			<%= f.submit "Comment", class: "btn btn-primary" %> 
			<% end %> 
			<br>
			<br>
			<br>

		</div>

		<% end %> 
	</div>
</div>

app/views/blogs/show.html.erb
<div id="single_post"> 
	<div class="row">
		<div class="col-md-3 col-md-offset-1">
			<h1> <%= @blog.content %> </h1>
			<p><%=  @blog.likes.count %> likes</p>
			<% if !Like.where("user_id =  ? and blog_id =  ?", current_user.id, @blog.id).any? %> 
			<%= button_to "Like", {:controller => :likes, :action => 'create', :blog_id => @blog.id, :user_id => current_user.id}, :method => "post", class: "btn btn-primary" %>

			<% else %> 
			<%= button_to "Unlike", {:controller => :likes, :action => 'destroy', :id => Like.where("user_id =  ? and blog_id =  ?", current_user.id, @blog.id).first }, :method => "delete", class: "btn btn-primary" %>

			<% end %> 
		</div>
	</div>

	<br>
	<div class="row">
		<div class="col-md-3 col-md-offset-1">
			<% @blog.comments.each do |c| %> 

			<p> <%= c.user.name %>: <%= c.content %> 
				<% if current_user.id == c.user_id %> 
				<%= button_to "Delete comment", {:controller => :comments, :action => 'destroy', :id => c.id}, :method => "delete", class: "btn btn-primary" %>
				<% end %> 	
			</p>
			<br>
			<% end %> 


		</div>


	</div>
	<div class="row">
		<div class="col-md-3 col-md-offset-1">

			<% if current_user.id ==  @blog.user.id %> 
			<%= button_to "Delete blog", {:controller => :blogs, :action => 'destroy', :id =>  @blog.id}, :method => "delete", class: "btn btn-danger" %>
			<br>
			<%= button_to "Edit blog", {:controller => :blogs, :action => 'edit', :id =>  @blog.id}, :method => "get", class: "btn btn-primary" %>
			<% end %>
		</div>


	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>MultiUserBlog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<% if flash[:errors] %>
		<%= flash[:errors] %>
		<% end %>


		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		     
		      <%= link_to 'Multi User Blog' , blogs_path, class: "navbar-brand" %> 
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		 
		
		      <ul class="nav navbar-nav navbar-right">
		      	<% if current_user %>

		      	<li> <%= link_to current_user.name, user_path(current_user) %></li>
		 		<li> <%= link_to "Edit Profile", edit_user_path(current_user) %></li>
		 		        <li><%= button_to "Log Out", {:controller => :sessions,
		 			:action => 'destroy', :id => session[:user_id] }, :method => :delete , class: "btn btn-primary" %></li>
		 		<% end %>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>


		<h1>  </h1> 



		
			
			

			<%= yield %>
		</div>
</body>
</html>

app/views/users/edit.html.erb
<h1 class="col-md-6 col-md-offset-4">Edit User</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<form class="form-horizontal">
			<div class="form-group">
				<%= form_for(@user) do |f| %> 
				<%= f.label :email, "Email", class: "control-label col-sm-2" %> 
				<div class="col-sm-10">
					<%= f.email_field :email, class: "form-control"%> 
				</div>
			</div>
			<div class="form-group">
				<%= f.label :name, "Name", class: "control-label col-sm-2"   %> 
				<div class="col-sm-10">
					<%= f.text_field :name, class: "form-control" %> 
					<br>
				</div>	
				<div class="row">
					<div class="control-label col-sm-2">
						<%= f.submit "Update", class: "btn btn-primary" %>
						<% end %> 
					</div>
					<div class="control-label col-sm-2">
						<%= button_to "Delete Account", {:controller => :users,
							:action => 'destroy', :id => session[:user_id] }, :method => :delete, class: "btn btn-danger" %>
						</div>
					</div>
				</div>
			</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %> 
		<%= f.label :email, "Email" %> 
		<%= f.email_field :email, class: 'form-control' %> 

		<%= f.label :name, "Name"  %> 
		<%= f.text_field :name, class: 'form-control' %> 

		<%= f.label :password, "Password" %> 
		<%= f.password_field :password, class: 'form-control' %> 

		<%= f.label :password_confirmation, "Password Confirmation" %> 
		<%= f.password_field :password_confirmation, class: 'form-control' %> 
		<br>
		<%= f.submit "Join", class: "btn btn-primary" %>
		<br>
		<br>
		<% end %> 
	</div>


</div>

app/views/users/show.html.erb
<div class="row">
	<h1 class="col-md-6 col-md-offset-4"> <%= current_user.name %>'s Blogs </h1>
</div>
<% @userBlog.each do |u| %> 
<div id="single_post"> 
	<p>  <%= link_to  u.content, blog_path(u.id), class: "navbar-brand" %></p> 
	<br>
	<br>
	<br>
	<p><%= u.likes.count %> likes</p>
	
	<% if !Like.where("user_id =  ? and blog_id =  ?", current_user.id, u.id).any? %> 
	<%= button_to "Like", {:controller => :likes, :action => 'create', :blog_id => u.id, :user_id => current_user.id}, :method => "post", class: "btn btn-primary" %>

	<% else %> 
	<%= button_to "Unlike", {:controller => :likes, :action => 'destroy', :id => Like.where("user_id =  ? and blog_id =  ?", current_user.id, u.id).first }, :method => "delete", class: "btn btn-primary" %>

	<% end %> 
	<% u.comments.each do |c|  %> 
	<p> <%= c.user.name %>: <%= c.content %> 
		<% if current_user.id == c.user_id %> 
		<%= button_to "Delete comment", {:controller => :comments, :action => 'destroy', :id => c.id}, :method => "delete", class: "btn btn-primary" %>
		<% end %> 	
	</p>
	<% end %> 


	<br>
	<%= button_to "Delete blog", {:controller => :blogs, :action => 'destroy', :id => u.id, }, :method => "delete", class: "btn btn-danger" %>
	<br>
	<%= button_to "Edit blog", {:controller => :blogs, :action => 'edit', :id => u.id}, :method => "get", class: "btn btn-primary" %>
	<br>

	<%= form_for(@comment, url: comments_path, html: {method: "post"}) do |f| %> 

	<%= hidden_field_tag(:blog_id, u.id) %>
	<%= hidden_field_tag(:user_id, current_user.id) %>

	<%=	f.label :content, "New Comment" %> 
	<%= f.text_field :content, class: 'form-control', placeholder: "Write a comment..." %> 
	<br>
	<%= f.submit "Comment", class: "btn btn-primary" %> 
	<% end %> 
</div>	


<% end %>
<br>
<br>
<br>
<%= form_for(@blog, url: blogs_path, html: {method: "post"}) do |f| %> 
<%=	f.label :content, "New Blog" %> 
<%= f.text_field :content, class: 'form-control' %> 
<br>
<%= f.submit "Create Blog", class: "btn btn-primary" %> 
<br>
<br>
<% end %> 